// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuneage.Data.Orm.EF.DataContexts;

namespace Tuneage.Data.Migrations
{
    [DbContext(typeof(TuneageDataContext))]
    [Migration("20190125095213_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tuneage.Domain.Entities.Artist", b =>
                {
                    b.Property<int>("ArtistId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("CredScoreSum");

                    b.Property<bool>("IsBand");

                    b.Property<bool>("IsPrinciple");

                    b.Property<string>("Name");

                    b.Property<string>("PopulismType")
                        .IsRequired();

                    b.HasKey("ArtistId");

                    b.ToTable("Artists");

                    b.HasDiscriminator<string>("PopulismType").HasValue("Artist");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.ArtistVariousArtistsRelease", b =>
                {
                    b.Property<int>("ArtistId");

                    b.Property<int>("VariousArtistsReleaseId");

                    b.HasKey("ArtistId", "VariousArtistsReleaseId");

                    b.HasIndex("VariousArtistsReleaseId");

                    b.ToTable("ArtistVariousArtistsReleases");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.Label", b =>
                {
                    b.Property<int>("LabelId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("WebsiteUrl");

                    b.HasKey("LabelId");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.PrimaryCredType", b =>
                {
                    b.Property<string>("PrimaryCredTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<decimal>("Weight");

                    b.HasKey("PrimaryCredTypeId");

                    b.ToTable("PrimaryCredTypes");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.Release", b =>
                {
                    b.Property<int>("ReleaseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsByVariousArtists");

                    b.Property<int>("LabelId");

                    b.Property<string>("ReleaseType")
                        .IsRequired();

                    b.Property<DateTime>("ReleasedOn");

                    b.Property<string>("Title");

                    b.Property<int>("YearReleased");

                    b.HasKey("ReleaseId");

                    b.HasIndex("LabelId");

                    b.ToTable("Releases");

                    b.HasDiscriminator<string>("ReleaseType").HasValue("Release");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.ConceptualArtist", b =>
                {
                    b.HasBaseType("Tuneage.Domain.Entities.Artist");

                    b.HasDiscriminator().HasValue("ConceptualArtist");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.PopulismArtist", b =>
                {
                    b.HasBaseType("Tuneage.Domain.Entities.Artist");

                    b.HasDiscriminator().HasValue("PopulismArtist");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.SingleArtistRelease", b =>
                {
                    b.HasBaseType("Tuneage.Domain.Entities.Release");

                    b.Property<int>("ArtistId");

                    b.HasIndex("ArtistId");

                    b.HasDiscriminator().HasValue("SA");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.VariousArtistsRelease", b =>
                {
                    b.HasBaseType("Tuneage.Domain.Entities.Release");

                    b.HasDiscriminator().HasValue("VA");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.AliasedArtist", b =>
                {
                    b.HasBaseType("Tuneage.Domain.Entities.ConceptualArtist");

                    b.Property<int>("PrincipleArtistId");

                    b.HasDiscriminator().HasValue("AliasedArtist");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.Band", b =>
                {
                    b.HasBaseType("Tuneage.Domain.Entities.PopulismArtist");

                    b.HasDiscriminator().HasValue("BAND");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.SoloArtist", b =>
                {
                    b.HasBaseType("Tuneage.Domain.Entities.PopulismArtist");

                    b.HasDiscriminator().HasValue("SOLO");
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.ArtistVariousArtistsRelease", b =>
                {
                    b.HasOne("Tuneage.Domain.Entities.Artist", "Artist")
                        .WithMany("ArtistVariousArtistsReleases")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tuneage.Domain.Entities.VariousArtistsRelease", "VariousArtistRelease")
                        .WithMany("ArtistVariousArtistsReleases")
                        .HasForeignKey("VariousArtistsReleaseId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.Release", b =>
                {
                    b.HasOne("Tuneage.Domain.Entities.Label", "Label")
                        .WithMany("Releases")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tuneage.Domain.Entities.SingleArtistRelease", b =>
                {
                    b.HasOne("Tuneage.Domain.Entities.Artist", "Artist")
                        .WithMany()
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
